### ISSUE TITLE
P9p spoof

### ISSUE THREAD

**Issue by cihaneken** [RisenID/HuskySpoof#5]
Is there a plan to implement P9P spoof for AI zoom enhancement? With P8p there is currently only Eraser and Stylize.

Edit: It seems that AI Zoom enhanced has different library or system apk dependencies. It crashes somehow.

**Comment by RisenID** [comment]
P9p spoof is already available here. 
https://github.com/RisenID/PixelSpoof/releases/tag/AD1A.240530.047.U1

As to what you can do with spoofing, it seems that google is tying a lot of features to the soc rather than just the model, so just spoofing the model seems to unlock less and less features as time goes on.
